Removed attachments for urls
Flame442/FlameCogs pull request #56
Opened 2020-11-08 04:18 UTC by TheWyn

It's much easier with url's when using it through another cog (Trusty's retrigger for one)

2020-11-08 04:31 UTC, Flame442 commented
You replaced tabs with spaces, if nothing else that needs to change since I cannot tell what the diff is...

2020-11-08 04:37 UTC, TheWyn commented
Removed message attachment for image url and included embed thumbnail url option.

Couldn't attach an image when wrapping this through another cog, thought it'd be helpful.

2020-11-08 06:07 UTC, Flame442 requested changes
This change does not function as expected, and I'm not sure how you would manage to make it function as you want to. Other behavior and stylistic choices modified in this PR should not be touched.

The point of this cog is to be a **very** simple embed cog, and I don't think it would be possible to support images via url in a non-complex way. If you can find one, I'm fine with considering it, but as it stands right now, this PR breaks functionality.

2020-11-08 06:07 UTC, Flame442 commented on simpleembed/simpleembed.py
> -		All normal discord formatting will work inside the embed.
This line should not be removed.

2020-11-08 06:07 UTC, Flame442 commented on simpleembed/simpleembed.py
> +	async def sendembed(self, ctx, color: Optional[discord.Color] = None, image=None, thumbnail=None, *, text):
This signature **requires** both an image and a thumbnail be provided.

2020-11-08 06:07 UTC, Flame442 commented on simpleembed/simpleembed.py
> -			pass
This should not be removed.

2020-11-08 10:18 UTC, TheWyn commented
Added to message delete back but couldn't figure out how to make those parameters optional, I thought `Optional[str] = None` would've worked but that only brought up the help menu.

2020-11-08 15:48 UTC, Flame442 commented
Since all the args (besides the first one) are of type `str`, they will all "want" to be used. The only way to make it not required would be to have something like `typing.Optional[LinkConverter]`, however such a converter would be unnecessarily complex for this cog.

2020-11-09 05:30 UTC, TheWyn commented
Ahk nevermind then.

2020-11-09 05:30 UTC, closed without merging